# Generated by Django 5.1 on 2026-04-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('cart', 'Cart'), ('purchase', 'Purchase'), ('search', 'Search')], max_length=20)),
                ('query', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interactions',
                'indexes': [models.Index(fields=['user_id', 'event_type'], name='interaction_user_id_cce0e0_idx')],
            },
        ),
    ]
